// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/experiences": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a list of experience data records with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiences"
                ],
                "summary": "List experience data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source ID",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by field ID",
                        "name": "field_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user identifier",
                        "name": "user_identifier",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of records to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_xernobyl_formbricks_worktrial_internal_models.ExperienceData"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new experience data record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiences"
                ],
                "summary": "Create experience data",
                "parameters": [
                    {
                        "description": "Experience data to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_xernobyl_formbricks_worktrial_internal_models.CreateExperienceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_xernobyl_formbricks_worktrial_internal_models.ExperienceData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/experiences/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a single experience data record by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiences"
                ],
                "summary": "Get experience data by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Experience ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_xernobyl_formbricks_worktrial_internal_models.ExperienceData"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Experience not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an experience data record by ID",
                "tags": [
                    "experiences"
                ],
                "summary": "Delete experience data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Experience ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - Successfully deleted"
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Experience not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing experience data record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experiences"
                ],
                "summary": "Update experience data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Experience ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_xernobyl_formbricks_worktrial_internal_models.UpdateExperienceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_xernobyl_formbricks_worktrial_internal_models.ExperienceData"
                        }
                    },
                    "400": {
                        "description": "Invalid request or UUID format",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Experience not found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_xernobyl_formbricks_worktrial_internal_models.CreateExperienceRequest": {
            "type": "object",
            "properties": {
                "collected_at": {
                    "type": "string"
                },
                "field_id": {
                    "type": "string"
                },
                "field_label": {
                    "type": "string"
                },
                "field_type": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "source_id": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        },
        "github_com_xernobyl_formbricks_worktrial_internal_models.ExperienceData": {
            "type": "object",
            "properties": {
                "collected_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "field_id": {
                    "type": "string"
                },
                "field_label": {
                    "type": "string"
                },
                "field_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "source_id": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        },
        "github_com_xernobyl_formbricks_worktrial_internal_models.UpdateExperienceRequest": {
            "type": "object",
            "properties": {
                "field_id": {
                    "type": "string"
                },
                "field_label": {
                    "type": "string"
                },
                "field_type": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "source_id": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and your API key.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Formbricks Hub API",
	Description:      "API for managing experience data collection",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
